export default {
  welcomeEn: 'WELCOME  TO  MY  WORLD',
  welcomeCn: 'Hi，这里是D.va的个人网站，很高兴认识你！',
  canIDo: 'What can | I do',
  skillInfo: '作为一名UI设计师，\n我擅长UI设计，包括移动端和网页端; \n擅长插画， \n包括运营插画和人物情绪版设计； \n能做简单的AE动效……',
  chooseme: 'Why you | choose me',
  choosemeDesc: '选我当然是因我过硬的技能、有趣的灵魂和微厚的…脸皮，哈哈~说正经的，专业技能方面，熟练掌握PS、AI、Axure 熟悉AE、Figma；个人突出特质方面，自学能力超棒（做设计以来从未间断练习）、情绪调节能力一流（毕竟心理学专业）、 统筹能力强（主持公司周年庆、草莓音乐节志愿者）',
  recentWork: 'My recent | works',
  recentWorkDesc: '近期作品包括公司项目和个人练习，\n公司项目以移动端为主;\n个人练习均为原创，有平时打卡也有比赛作品。',
  personalSkill: 'PERSONA | SKILLS',
  personalSkillDesc: '拥有计算机二级、英语六级、心理咨询师三级、普通话二甲证书',
  basicInfo: 'BASIC | INFORMATION',
  workExperience: 'WORK | EXPERIENCE',
  workFlootTextCn: '凡是过往皆为序章，所有未来皆为可盼!',
  workFlootTextEn: 'All the past is the prologue, all the future is the hope!',
  sloganCn: '设计|是我第一个|无关他人|的决定，我会保持初心，走好这条路！',
  sloganEn: 'Design is my first decision that has nothing to do with others, \nI will keep my original intention and take this path well!',
  sloganAt: '@一只努力进步的设计崽',
  myColleague: 'Be my | colleague?',
  callme: '快和我成为同事吧！简单粗暴联系我！',
  phone: '15071437560',
  email: '973773273@qq.com'
}